def get_face_north(face):                           return face["north"]
def get_face_east(face):                            return face["east"]
def get_face_south(face):                           return face["south"]
def get_face_west(face):                            return face["west"]
def get_face_up(face):                              return face["up"]
def get_face_down(face):                            return face["down"]
def get_face_direction_uv(face_direction):          return face_direction["uv"]
def get_face_direction_texture(face_direction):     return face_direction["texture"]